# 1: PyTorch

Når man er blevet mere vant til nogle af de muligheder Python i sig selv tilbyder, er det almindeligt at udvide Pythons repertoire ved at **importere pakker**. Pakker er udvidelser til Python med færdige funktioner og datatyper.

I dette afsnit bruger vi **PyTorch** til basale matematiske operationer og manipulation af numeriske data. PyTorch kan også bruges til maskinlæring, men her arbejder vi kun med pakkens grundlæggende datatype: en **tensor**.

En tensor er en samling tal. En tensor med én dimension minder om en matematisk vektor, og en tensor med to dimensioner minder om en matematisk matrix.

PyTorch importeres normalt sådan:


In [167]:
import torch

Nu kan vi bruge pakkens funktioner ved at skrive `torch` efterfulgt af et punktum og funktionens navn. En tensor oprettes med funktionen `torch.tensor()`:


In [168]:
min_tensor = torch.tensor([1, 2, 3])

print(min_tensor)

tensor([1, 2, 3])


Inputtet til `torch.tensor()` er her en Python-liste med tallene `1`, `2` og `3`. PyTorch omdanner listen til en tensor.

Tensorer understøtter aritmetiske operationer som addition og subtraktion. Operationerne udføres element for element, når tensorerne har samme form.


In [169]:
# Her lægger vi to tensorer sammen og trækker dem fra hinanden
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([0, 0, 1])

tensor_sum = tensor_1 + tensor_2
tensor_differens = tensor_1 - tensor_2

print("sum:", tensor_sum)
print("differens:", tensor_differens)

sum: tensor([1, 2, 4])
differens: tensor([1, 2, 2])


Man kan hente enkelte tal fra en tensor med firkantede parenteser `[]`.


In [170]:
min_tensor = torch.tensor([1, 2, 3])

første_tal = min_tensor[0]
andet_tal = min_tensor[1]
tredje_tal = min_tensor[2]

print("første_tal:", første_tal,
      "\n andet_tal:", andet_tal,
      "\n tredje_tal:", tredje_tal)

første_tal: tensor(1) 
 andet_tal: tensor(2) 
 tredje_tal: tensor(3)


Det at referere til bestemte elementer i en række på denne her måde kaldes **indeksering**. Her skal man være opmærksom på, at Python nul-indekserer. Det betyder bare, at man starter fra nul, når man tæller.

Man kan bruge `len()` til at få længden af en tensor. Tensorer har ikke en `.append()`-metode som Python-lister (som i vil lære om senere). I stedet kan man oprette en ny tensor ved at kæde tensorer sammen med `torch.cat()`.


In [171]:
min_tensor = torch.tensor([1, 2, 3])

print("min_tensor:", min_tensor)
print("Længden af min_tensor:", len(min_tensor))

min_tensor = torch.cat((min_tensor, torch.tensor([4])))

print("min_tensor:", min_tensor)
print("Længden af min_tensor:", len(min_tensor))

min_tensor: tensor([1, 2, 3])
Længden af min_tensor: 3
min_tensor: tensor([1, 2, 3, 4])
Længden af min_tensor: 4


Tensorer med én dimension minder om vektorer fra matematik og er nyttige til numeriske data. Man kan lægge to tensorer i forlængelse af hinanden med `torch.cat()`. Tensorerne skrives i en tuple, og `dim=0` angiver, at de kædes sammen langs den første dimension.


In [172]:
# Her lægger vi to tensorer i forlængelse af hinanden
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([0, 0, 1])

samlet_tensor = torch.cat((tensor_1, tensor_2), dim=0)

print(samlet_tensor)

tensor([1, 2, 3, 0, 0, 1])


PyTorch kan også bruges til matricer. En matrix repræsenteres som en todimensionel tensor: en samling rækker og kolonner.


In [173]:
min_matrix = torch.tensor([[1, 2], [3, 4]])

print(min_matrix)

tensor([[1, 2],
        [3, 4]])


Matricer kan lægges sammen og trækkes fra hinanden med `+` og `-`. Operatoren `*` ganger element for element, mens `@` udfører matrixmultiplikation.


In [174]:
matrix_1 = torch.tensor([[1, 2], [3, 4]])
matrix_2 = torch.tensor([[2, 2], [2, 2]])

matrix_sum = matrix_1 + matrix_2
matrix_differens = matrix_1 - matrix_2
matrix_produkt = matrix_1 @ matrix_2

print("matrix_sum:\n", matrix_sum,
      "\n matrix_differens:\n", matrix_differens,
      "\n matrix_produkt:\n", matrix_produkt)

matrix_sum:
 tensor([[3, 4],
        [5, 6]]) 
 matrix_differens:
 tensor([[-1,  0],
        [ 1,  2]]) 
 matrix_produkt:
 tensor([[ 6,  6],
        [14, 14]])


To endimensionelle tensorer har også et **prikprodukt**, som kan beregnes med `torch.dot()`.


In [175]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([0, 0, 1])

prikprodukt = torch.dot(tensor_1, tensor_2)

print(prikprodukt)

tensor(3)


Man kan også transponere matricer. At transponere en matrix betyder at bytte om på rækker og kolonner.

In [176]:
min_matrix = torch.tensor([[1, 2], [3, 4]])

min_transponerede_matrix = min_matrix.T

print("min_matrix:\n", min_matrix,
      "\n min_transponerede_matrix:\n", min_transponerede_matrix)

min_matrix:
 tensor([[1, 2],
        [3, 4]]) 
 min_transponerede_matrix:
 tensor([[1, 3],
        [2, 4]])


At kende en tensors **form** er også nyttigt. Egenskaben `.shape` fortæller, hvor mange elementer tensoren har langs hver dimension.


In [177]:
min_matrix = torch.tensor([[1, 2], [3, 4]])

min_matrix_dimension = min_matrix.shape

print(min_matrix_dimension)

torch.Size([2, 2])


Vores matrix har formen $2 × 2$. Ved større datasæt er `.shape` praktisk til at kontrollere, om tensorerne har de forventede dimensioner.

PyTorch vælger automatisk en **datatype** ud fra tallene. Hele tal bliver typisk `torch.int64`, mens decimaltal typisk bliver `torch.float32`. Funktioner som `mean()`, `var()` og `torch.linalg.inv()` kræver decimaltal, så i de tilfælde opretter vi tensoren med `dtype=torch.float32`.

| PyTorch-funktion eller egenskab | Beskrivelse |
|---|---|
| `torch.sin(a)` | Beregner sinus elementvist. |
| `torch.cos(a)` | Beregner cosinus elementvist. |
| `torch.tan(a)` | Beregner tangens elementvist. |
| `torch.exp(a)` | Beregner $e^x$ elementvist. |
| `torch.pi` | Værdien af pi. |
| `a.mean()` | Gennemsnittet af alle elementer. Brug `dim=...` for en bestemt dimension. |
| `a.var(correction=0)` | Variansen af elementerne. `correction=0` giver populationens varians. |
| `a.std(correction=0)` | Standardafvigelsen af elementerne. |
| `torch.zeros(n)` | Opretter en tensor med `n` nuller. |
| `torch.dot(a, b)` | Prikproduktet af to endimensionelle tensorer. |
| `torch.linalg.inv(a)` | Den inverse af en kvadratisk tensor med decimaltal. |
| `a.T` | Transponerer en todimensionel tensor. |
| `a.shape` | Tensorens form. |
| `@` | Matrixmultiplikation. |


En matrix er en todimensionel tensor. Derfor bruger man to indeks: først rækken og derefter kolonnen.


In [178]:
min_matrix = torch.tensor([[1, 2], [3, 4]])

første_række = min_matrix[0]
første_tal = min_matrix[0, 0]

print("Første række:", første_række,
      "\n Første tal i første række:", første_tal)

Første række: tensor([1, 2]) 
 Første tal i første række: tensor(1)


Man kan også udvælge et interval af en tensor med kolon. Dette kaldes **slicing**.


In [179]:
min_tensor = torch.tensor([6, 4, 2, 0, 9])

print(min_tensor[1:4])

tensor([4, 2, 0])


Et kolon uden tal betyder, at hele dimensionen vælges. Det kan for eksempel bruges til at vælge en hel kolonne.


In [180]:
min_matrix = torch.tensor([[1, 2], [3, 4]])

print(min_matrix[:, 0])

tensor([1, 3])


Her skal det forstås som at man tager alle rækker (derfor brug af kolon) men kun første kolonne (derfor brug af 0-indeksering). Her kommer der lidt flere eksempler man kan bruges som opslagsværk.

In [181]:
matrix_1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_2 = torch.tensor([[4, -1, 6], [2, 8, -3], [2, -4, -5]])

print("Summen af de 2 første tal i anden række i første matrix og de 2 første tal i tredje række i anden matrix:", matrix_1[1, 0:2] + matrix_2[2, 0:2])
print("Differensen mellem de 2 første tal i sidste kolonne i første matrix og de 2 første tal i næstsidste kolonne i anden matrix:", matrix_1[0:2, -1] - matrix_2[0:2, -2])

Summen af de 2 første tal i anden række i første matrix og de 2 første tal i tredje række i anden matrix: tensor([6, 1])
Differensen mellem de 2 første tal i sidste kolonne i første matrix og de 2 første tal i næstsidste kolonne i anden matrix: tensor([ 4, -2])


Her er en tabel over typiske PyTorch-funktioner til at manipulere tensorer.

| PyTorch-funktion eller skrivemåde | Beskrivelse |
|---|---|
| `torch.tensor(data)` | Opretter en tensor ud fra fx en Python-liste. |
| `a[i]` | Elementet på position `i` (nul-indekseret). |
| `a[-1]` | Sidste element; `-2` er næstsidste osv. |
| `a[start:stop]` | Udsnit fra `start` til, men ikke med, `stop`. |
| `a[:, 0]` | Alle rækker i første kolonne. |
| `torch.cat((a, b), dim=0)` | Kæder tensorer sammen langs en eksisterende dimension. |
| `torch.stack((a, b), dim=0)` | Samler tensorer langs en ny dimension. |
| `torch.hstack((a, b))` | Samler tensorer vandret. |
| `torch.vstack((a, b))` | Samler tensorer lodret. |
| `torch.tensor_split(a, dele, dim=0)` | Deler en tensor langs en dimension. |
| `a.reshape(ny_form)` | Giver tensoren en ny form med samme data. |
| `a.flatten()` | Flader tensoren ud til én dimension. |
| `a.shape` | Tensorens form (dimensioner). |


### Opgaver

##### Opgave 1.1
Definer to PyTorch-tensorer med samme længde. Print derefter:

- Teksten "mine tensorer:" efterfulgt af de to tensorer
- Første element i den første tensor
- Summen af tensorerne
- Det elementvise produkt af tensorerne
- Differensen mellem første tal i den første tensor og andet tal i den anden
- En sammensætning af begge tensorer med `torch.cat()`


In [182]:
# Din kode her

##### Opgave 1.2
Tilføj et tal til den første tensor fra opgave 1.1 ved hjælp af `torch.cat()`. Læg derefter længden af den nye tensor sammen med længden af den anden tensor.


In [183]:
# Din kode her

##### Opgave 1.3
Definer følgende to matricer som PyTorch-tensorer

$$
A =
\begin{bmatrix}
8 & 32 \\
9 & 1
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
5 & 4 \\
2 & 6
\end{bmatrix}
$$

Beregn følgende:

- $A + B$
- $A - B$
- $AB$
- $A^TB$

In [184]:
# Din kode her

##### Opgave 1.4
Tag udganspunkt i matricerne $A$ og $B$ fra før. Beregn følgende:
- Summen af første række i $A$ og anden række i $B$
- Differensen mellem første kolonne i $A$ og anden kolonne i $B$
- Produktet af første tal i første række i $A$ og andet tal af anden række i $B$

In [185]:
# Din kode her

# 2: Løkker

En computer er rigtig god til at gentage sig selv, og gøre den samme handling igen og igen. For at fortælle Python, at vi gerne vil have en handling
gentaget, så skal vi gøre brug af løkker.

En `for`-løkke er lavet til at gentage en handling for hvert tal i en tensor.


In [186]:
min_tensor = torch.tensor([0, 1, 2, 3, 4])

for i in min_tensor:
    print(i)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)


Koden skal læses som: vi lader variablen i referere skiftevis til hvert
tal i tensoren og printer tallet, for hver iteration. Eksemplet ovenfor er lidt banalt, da vi har en tensor, der bare tæller op, så lad os se på nogle flere eksempler.

In [187]:
min_tensor = torch.tensor([3, 2, 9, -2, 0.2])

print("for-løkke der printer tal i en tensor:")
for i in min_tensor:
    print(i)

print("for-løkke der printer tal i en tensor efterfulgt af udråbstegn:")
for i in min_tensor:
    print(i, "!")

print("\nfor-løkke der printer alle tal i en tensor plus 2")
for i in min_tensor:
    print(i+2)

print("\nfor-løkke der printer alle tal i en tensor med en værdi større end 2")
for i in min_tensor:
    if i>=2:
        print(i)

for-løkke der printer tal i en tensor:
tensor(3.)
tensor(2.)
tensor(9.)
tensor(-2.)
tensor(0.2000)
for-løkke der printer tal i en tensor efterfulgt af udråbstegn:
tensor(3.) !
tensor(2.) !
tensor(9.) !
tensor(-2.) !
tensor(0.2000) !

for-løkke der printer alle tal i en tensor plus 2
tensor(5.)
tensor(4.)
tensor(11.)
tensor(0.)
tensor(2.2000)

for-løkke der printer alle tal i en tensor med en værdi større end 2
tensor(3.)
tensor(2.)
tensor(9.)


En anden meget nyttig funktion i forbindelse med løkker er `range()`. `range()` genererer en række tal, som en `for`-løkke kan iterere over. Den bruges ofte, når man vil gentage en handling et bestemt antal gange, eller når man har brug for at iterere med et indeks.

Syntaksen for `range()` kan være:
- `range(stop)`: Genererer tal fra 0 op til (men ikke med) `stop`.
- `range(start, stop)`: Genererer tal fra `start` op til (men ikke med) `stop`.
- `range(start, stop, step)`: Genererer tal fra `start` op til (men ikke med) `stop`, med et spring på `step`.

In [188]:
print("Eksempel med range(5):")
for i in range(5):
    print(i)

print("\nEksempel med range(2, 7):")
for i in range(2, 7):
    print(i)

print("\nEksempel med range(0, 10, 2):")
for i in range(0, 10, 2):
    print(i)

# Brug af range til at iterere gennem en tensors elementer ved indeks
min_tensor = torch.tensor([10, 20, 30, 40])
print("\nItererer gennem en tensor med range(len(tensor)):")
for i in range(len(min_tensor)):
    print(f"Element på indeks {i}: {min_tensor[i]}")

Eksempel med range(5):
0
1
2
3
4

Eksempel med range(2, 7):
2
3
4
5
6

Eksempel med range(0, 10, 2):
0
2
4
6
8

Itererer gennem en tensor med range(len(tensor)):
Element på indeks 0: 10
Element på indeks 1: 20
Element på indeks 2: 30
Element på indeks 3: 40


Man behøver ikke bruge bogstavet $i$ som indeks i en `for`-løkke, men det er en konvention, som vi anbefaler at følge. Vær opmærksom på brug af $[i]$ i forhold til $i$ til indeksering i en `for`-løkke. Man kan også lave såkaldte "nestede" løkker, som er løkker i andre løkker. Her bliver man nødt til at bruge flere forskellige bogstaver til indeksering, hvilket hurtigt bliver meget nørklet, men kan være brugbart.

Betragt nedenstående eksempler.

In [189]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([2, 2, 2, 2, 2, 2])

for i in tensor_1:
    for j in tensor_2:
        print("waouw sejt tal", i+j)

waouw sejt tal tensor(3)
waouw sejt tal tensor(3)
waouw sejt tal tensor(3)
waouw sejt tal tensor(3)
waouw sejt tal tensor(3)
waouw sejt tal tensor(3)
waouw sejt tal tensor(4)
waouw sejt tal tensor(4)
waouw sejt tal tensor(4)
waouw sejt tal tensor(4)
waouw sejt tal tensor(4)
waouw sejt tal tensor(4)
waouw sejt tal tensor(5)
waouw sejt tal tensor(5)
waouw sejt tal tensor(5)
waouw sejt tal tensor(5)
waouw sejt tal tensor(5)
waouw sejt tal tensor(5)


In [190]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

indeks_tensor = torch.tensor([0, 1, 2])
matrix_par_sum = []

for i in indeks_tensor:
    for j in indeks_tensor:
        matrix_par_sum.append(matrix[i, j] + matrix[j, i])

matrix_par_sum = torch.stack(matrix_par_sum)
print("matrix_par_sum:", matrix_par_sum)

matrix_par_sum: tensor([ 2,  6, 10,  6, 10, 14, 10, 14, 18])


### Opgaver

##### Opgave 2.1
Følgende kode printer alle tal i en tensor plus $2$. Ændr den, så den i stedet printer alle tal i tensoren ganget med $5$.

In [191]:
min_tensor = torch.tensor([0, 1, 2, 3, 4])

for i in min_tensor:
    print(i + 2)

tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)


##### Opgave 2.2
Lav et program, der definerer en tensor og en `for`-løkke, der kvadrerer (opløfter i anden) alle tal i tensoren.

In [192]:
# Din kode her

##### Opgave 2.3
Lav et program, der definerer en tensor og en `for`-løkke, der trækker de sidste $3$ tal i tensoren fra de første $3$ tal i tensoren.

In [193]:
# Din kode her

##### Opgave 2.4
Skriv et program, der definerer en tensor, og derefter udskriver summen af tallene i tensoren ved hjælp af en løkke.

In [194]:
# Din kode her

##### Opgave 2.5
Skriv et program, der definerer en tensor og printer "jeg kan lide kage", for hver gang der er et negativt tal i tensoren.

In [195]:
# Din kode her

##### Opgave 2.6
Skriv et program, der indlæser en tensor af tal og udskriver det
mindste tal i tensoren efterfulgt af det første tal i tensoren.

In [196]:
# Din kode her

##### Opgave 2.7
Brug `range()` til at skrive et program, der printer tallene fra 1 til 10 (begge inklusive) i en for-løkke.

In [197]:
# Din kode her

# 3: Funktioner

Funktioner er en af de grundlæggende måder at strukturere sin kode på. De gør det nemmere at gentage beregninger, og kan gøre kode mere ordnet. Lad os først starte med at kigge på et eksempel på, hvorfor funktioner er brugbare.

In [198]:
a = 3
b = 4

c = (a**2 + b**2)**(1/2)

print(c)

a = 5
b = 12

c = (a**2 + b**2)**(1/2)

print(c)

a = 6
b = 8

c = (a**2 + b**2)**(1/2)

print(c)

5.0
13.0
10.0


Her beregner og printer vi $c$ i Pythagoras læresætning $3$ gange på præcis samme måde hver gang. Hvis man i stedet havde en funktion der lavede beregningen og printede, for forskellige værdier af $a$ og $b$, så ville man undgå at skulle skrive hele smøren op om og om igen. I tilfældet her vil det se ud som følgende:

In [199]:
def pythagoras(a, b):
    c = (a**2 + b**2)**(1/2)
    print(c)

pythagoras(3, 4)
pythagoras(5, 12)
pythagoras(6, 8)

5.0
13.0
10.0


Ligesom med betingelsessætninger skrives en funktion op med et nøgleord (her er det *def* i stedet for eksempelvis *if*) paranteser, kolonner og indryk. Her giver vi dog funktionen en navn (pythagoras her), der så skrives op, når vi kalder (bruger) funktionen.

Helt kort fortalt er følgende skabelonen for at definere sin egen funktion:

In [200]:
# def <funktionsnavn>(<arg1>,<arg2 >,...):
    # kode. Funktionens "krop".
    # return <værdi> # Valgfri

En funktionsdefinition består af 4 forskellige elementer:

- Et **navn**: Dette er navnet, man bruger, når man skal kalde en funktion:
I eksemplet er navnet pythagoras. Når man definerer en funktion, skal
man altid skrive def inden da, så Python ved, at der er tale om en
funktion.
- En **krop**: Dette er koden, som kører, når funktionen bliver kaldt,
altså når der er et stykke kode, som beder om at køre funktionen.
Eksemplets krop er linjen $c = (a**2 + b**2)**(1/2)$.
- En række **argumenter** (valgfrit): Dette er input, som funktionen
modtager, og kaldes også for parametre. Eksemplet tager $1$ argument:
liste, som skal være en liste af tal. Det er muligt at have funktioner, der modtager $0$ argumenter,
så skriver man ingenting imellem parenteserne, men parenteserne skal
stadig være der.
- En **returværdi** (valgfrit): Det er dette resultat, som funktionen giver
tilbage til det stykke kode, der kaldte den. Eksemplet ovenfor har ikke noget returelement, men vi ser senere på eksempler med returværdier.

Lad os se på lidt flere eksempler på funktioner

In [201]:
def f(x):
    y = 2 * x + 2
    return y

print("Lineær funktion y = 2 * x + 2 kaldt på 2:", f(2))
print("Lineær funktion y = 2 * x + 2 kaldt på 3:", f(3))
print("Lineær funktion y = 2 * x + 2 kaldt på 4:", f(4))

Lineær funktion y = 2 * x + 2 kaldt på 2: 6
Lineær funktion y = 2 * x + 2 kaldt på 3: 8
Lineær funktion y = 2 * x + 2 kaldt på 4: 10


In [202]:
def kvadrer_tal_i_tensor(tensor):
    for tal in tensor:
        print(tal**2)

sej_tensor = torch.tensor([2, 3, 4])
print(kvadrer_tal_i_tensor(sej_tensor))

tensor(4)
tensor(9)
tensor(16)
None


Ovenstående funktion virker på tensorer, men ikke på enkelte tal, fordi den forsøger at iterere gennem sit input. Bemærk, at der bliver printet `None`, fordi funktionen ikke har en returværdi.

Bemærk her at vi anvender en python liste til `resultater`- i lærer mere om lister snart, men indtil da så bare tænk på det som en hel normal liste. `.append` tilføjer blot en ny værdi til listens indhold.

In [203]:
def pølsechef_her_hvad_kunne_du_tænke_dig(episk_pølsebestilling):
    resultater = []
    for pølle in episk_pølsebestilling:
        pølle += 1
        resultater.append(f(pølle))

    resultater = torch.stack(resultater)
    print("Her værsgo bro der har du din episke ristede bro håber du har en god dag jeg hader virkelig mit arbejde xd", resultater)

jeg_kunne_godt_tænke_mig_en_ristet_med_det_hele_tak = torch.tensor([2, 3, 4])
pølsechef_her_hvad_kunne_du_tænke_dig(jeg_kunne_godt_tænke_mig_en_ristet_med_det_hele_tak)

Her værsgo bro der har du din episke ristede bro håber du har en god dag jeg hader virkelig mit arbejde xd tensor([ 8, 10, 12])


Faktisk har vi allerede set flere funktioner, blandt andet `print()`, `torch.tensor()` og `len()`. Det at bruge funktioner er altså ikke helt nyt, men nu kan du selv være med til at lave dem (8


### Opgaver


##### Opgave 3.1
Lav et program der tager et tal $x$ som input og returnerer $x + 2$.

In [204]:
# Din kode her

##### Opgave 3.2
Lav et program med en funktion der berenger $y = 2 \cdot x^2 + 2$ med $y$ som returværdi og $x$ som input. Print derefter resultatet af, at kalde funktionen på 3 forskellige input.

In [205]:
# Din kode her

##### Opgave 3.3
Lav et program med en funktion, der tager en tensor som input og returnerer gennemsnittet af tallene i tensoren.

In [206]:
# Din kode her

##### Opgave 3.4
Skriv et program som afgører, hvorvidt en matrix er symmetrisk eller ej. Her menes der
med symmetrisk at matricen opfylder $A^T = A$

In [207]:
# Din kode her

##### Opgave 3.5
Skriv et program som finder og returnerer middelværdien og variansen af hver række i en vilkårlig matrix. Hint: Brug tabellen over indbyggede PyTorch-funktioner. Husk at bruge en tensor med decimaltal, fx `dtype=torch.float32`.

In [208]:
# Din kode her

##### Opgave 3.6
En andengradsligning er en ligning på formen $ax^2 +bx+c =
0$, hvor målet er at finde x. Skriv et program med en funktion, der tager 3 input $a$, $b$ og $c$ og printer antallet af løsninger til ligningen, samt
løsningerne til ligningen, hvis de findes.

Antallet af løsninger kan bestemmes ud fra diskriminanten $d = b^2 − 4ac$
som følger:

- $d < 0$: Der findes ingen reelle løsninger.
- $d = 0$: Der findes én løsning $x = \frac{-b}{2a}−b$
- $d > 0$: Der findes to løsninger givet ved $x = \frac{−b±\sqrt{d}}{2a}$

In [209]:
# Din kode her

# 4: Lister og dictionaries

Indtil nu har vi arbejdet med tensorer, som er oplagte når man har numerisk data man vil regne på. Nogle gange har man dog data der ikke er tal, eller data der ikke passer ind i et pænt gitter. Her kommer **lister** ind i billedet

**Lister** er Pythons måde at gemme en samling af ting på. De minder meget om tensorer, men kan indeholde forskellige typer data fremfor kun tal, og man behøver ikke importere noget for at bruge dem, da de er et indbygget værktøj i python.

In [210]:
# En liste laves med firkantede parenteser
frugter = ["æble", "banan", "citron"]
tal = [3, 1, 4, 1, 5, 9]
blandet = [42, "tekst", 3.14, True]

# Man kan tilgå elementer ligesom med tensorer (nul-indekseret)
print(frugter[0])      # "æble"
print(frugter[-1])     # "citron" (negativ index tæller bagfra)

# Man kan tilføje elementer med .append()
frugter.append("drage")
print(frugter)         # ["æble", "banan", "citron", "drage"]

# Og man kan slice ligesom med tensorer
print(tal[1:4])        # [1, 4, 1]

# Længden findes med len()
print(len(frugter))    # 4

# Løkker virker også
for frugt in frugter:
    print(frugt)

æble
citron
['æble', 'banan', 'citron', 'drage']
[1, 4, 1]
4
æble
banan
citron
drage


På overfladen lyder lister smartere, men de håndterer matematiske operationer på en helt anden måde

In [211]:
liste_a = [1, 2, 3]
liste_b = [6, 7, 69]

print(liste_a + liste_b)

[1, 2, 3, 6, 7, 69]


Tommelfingerreglen er at bruge tensorer til numeriske data, man vil regne på, og lister til samlinger af ting, der ikke nødvendigvis er tal.


**Dictionaries** er en anden måde at gemme data på, men i stedet for at tilgå elementer via et indeks-tal, bruger man nøgler (keys). Tænk på det som en ordbog: du slår et ord op (nøglen) og får en forklaring (værdien).

In [212]:
# En dictionary laves med krøllede parenteser
person = {
    "navn": "Anna",
    "alder": 17,
    "klasse": "2.g",
    "interesser": ["matematik", "astronomi", "kodning"]
}

# Man tilgår værdier via nøglen
print(person["navn"])          # "Anna"
print(person["interesser"][1]) # "astronomi"

# Man kan tilføje nye nøgle-værdi-par
person["skole"] = "HTX Lyngby"
print(person["skole"])         # "HTX Lyngby"

# Man kan også ændre eksisterende værdier
person["alder"] = 18

Anna
astronomi
HTX Lyngby


Man kan loope over en dictionary på flere måder

In [213]:
# Looper over nøglerne
for nøgle in person:
    print(nøgle, "→", person[nøgle])

# Eller begge dele på én gang med .items()
for nøgle, værdi in person.items():
    print(f"{nøgle}: {værdi}")

navn → Anna
alder → 18
klasse → 2.g
interesser → ['matematik', 'astronomi', 'kodning']
skole → HTX Lyngby
navn: Anna
alder: 18
klasse: 2.g
interesser: ['matematik', 'astronomi', 'kodning']
skole: HTX Lyngby


Dictionaries er praktiske når man har data der naturligt kan "mærkes" med et navn fremfor et index Eksempelvis kunne man finde på at bruge dictionaries ofte til at gemme hyperparametre og resultater, når man laver machine learning (mere om det senere)

In [214]:
resultater = {
    "model_1 (lineær regression)": {"R2": 0.87, "grad": 1},
    "model_2 (neuralt netværk)": {"R2": 0.93, "grad": 2},
    "model_3 (Support Vector Machines)": {"R2": 0.91, "grad": 3},
}

for navn, resultat in resultater.items():
    print(f"{navn}: R²={resultat['R2']}, polynomiegrad={resultat['grad']}")

model_1 (lineær regression): R²=0.87, polynomiegrad=1
model_2 (neuralt netværk): R²=0.93, polynomiegrad=2
model_3 (Support Vector Machines): R²=0.91, polynomiegrad=3


Her kan det give bedre mening at bruge navnet på modellen som nøgle fremfor indeks, da det gør koden mere læsbar og selvforklarende.

### Opgaver

##### Opgave 2.1

Opret en liste med mindst fem af dine yndlingsfilm. Brug derefter en løkke til at printe hver film med et nummer foran, så eksempelvis
1. Interstellar
2. The Matrix
3. Kung Fury
osv.

Hint: Du kan bruge `range(len(filmliste))` eller `enumerate()` til at få både index og film; $\\$
altså en for løkke af formen `for index in range(len(filmliste))` for at få listens indekser, eller `for indeks, film in enumerate(filmliste)` for at få både indekset og værdien i listen samtidigt.

In [215]:
# Din kode her

##### Opgave 2.2

Opret en dictionary der beskriver dig selv. Som minimum skal den indeholde dit navn, din alder, din skole og en liste af dine interesser. Brug derefter en løkke med `.items()` til at printe alt informationen pænt.

In [216]:
# Din kode her

##### Opgave 2.3

Lav en dictionary kaldet vareliste der simulerer en indkøbskurv med mindst fem varer og deres priser, så eksempelvis

vareliste = {
    "mælk": 12,
    "brød": 20,
    "æg": 25,
    ...
}

Brug derefter en løkke til at beregne og printe den samlede pris for alle varer i indkøbskurven.

Hint: Start med en variabel `total = 0` og læg prisen fra hver vare til i løkken.

In [217]:
# Din kode her

# 5: Klasser og moduler

I Python er næsten alt, man arbejder med, et **objekt**. Et objekt samler data og de funktioner, der hører til dataene. Objekter af samme slags tilhører den samme **klasse**. Man kan tænke på klassen som typen eller opskriften der beskriver hvad et objekt består af- en nem måde at samle forskellig men relateret kode under en paraply

Forestil dig f.eks. at du var i gang med at lave koden til en bil i et spil. Du har måske brug for at beskrive bilens lokation, hastighed- måske en funktion der får bilen til at accellerere. Arbejdede du bare derudaf, kunne du nok godt ende med et program som indeholdte alt din ønskede funktionalitet $\\$
Din kode ville dog hurtigt ende med at virke mindre som den sammenhængende kode for at kunne beskrive en bil, i stedet virkende mere som en stor, usorteret bunke funktionalitet der blot tilfældigvis kunne bruges til at beskrive en bil når samlet. Din kode ville måske virke- men det ville være enormt grimt og uoverskueligt. $\\$
Det ville være federe hvis du i stedet bare kunne gruppere hele bilens funktionaliteten under en enkelt paraply. Dette er pointen med klasser- at kunne gruppere kode.

Man behøver ikke selv at kunne skrive klasser for at bruge dem- du har faktisk allerede gjort brugt af dem. $\\$
Når vi laver en tensor, får vi for eksempel et objekt fra PyTorchs `Tensor`-klasse:

```python
tal = torch.tensor([1.0, 2.0, 3.0])

print(type(tal))  # Klassen er torch.Tensor
print(tal.shape)  # En egenskab: information gemt på objektet
print(tal.mean()) # En metode: en funktion, der kaldes på objektet
```

Punktummet kan derfor læses som »noget, der hører til«. I `tal.mean()` er `mean()` en **metode**, der hører til tensoren `tal`. I `tal.shape` er `shape` en **egenskab**, så der bruges ingen parenteser.

Et **modul** er en Python-fil med kode, man kan importere. En **pakke** er typisk en samling af moduler. Importen giver os et navn, som samler modulets funktioner, klasser og værdier.

Ved siden af denne notebook ligger filen `eksempel_modul.py`. Den indeholder variablen `BESKED` og funktionerne `læg_sammen()` og `kvadrer()`. Filnavnet uden `.py` bruges, når modulet importeres:

Det vigtigste er altså at kunne genkende forskellen:

- `torch.tensor(...)`: en funktion fra pakken `torch`.
- `tal.mean()`: en metode på objektet `tal`.
- `tal.shape`: en egenskab på objektet `tal`.
- `eksempel_modul.kvadrer(...)`: en funktion fra vores egen fil `eksempel_modul.py`.


Nedenstående celle henter et modul til collab fra vores github repo.

In [221]:
import sys
import os

# Hent 'eksempel_modul.py' direkte med wget
# Denne URL er for den rå fil, ikke GitHub-sides visning af filen.
!wget https://raw.githubusercontent.com/UNF-Science-Camps/KIC26/main/00-Intro-Til-Programmering/eksempel_modul.py -O /content/eksempel_modul.py

# Angiv stien til mappen, der indeholder 'eksempel_modul.py'.
# Når filen downloades til /content/, skal stien være /content/.
module_path = '/content'

# Tilføj stien til Pythons søgesti
if module_path not in sys.path:
    sys.path.append(module_path)

print(f"'{module_path}' er nu tilføjet til sys.path.")
print("Når du har kørt denne celle, kan du prøve at importere 'eksempel_modul'.")

--2026-07-26 12:54:04--  https://raw.githubusercontent.com/UNF-Science-Camps/KIC26/main/00-Intro-Til-Programmering/eksempel_modul.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 258 [text/plain]
Saving to: ‘/content/eksempel_modul.py’

/content/eksempel_m 100%[===================>]     258  --.-KB/s    in 0s      

2026-07-26 12:54:04 (5.83 MB/s) - ‘/content/eksempel_modul.py’ saved [258/258]

'/content' er nu tilføjet til sys.path.
Når du har kørt denne celle, kan du prøve at importere 'eksempel_modul'.


Her bliver der importeret et modul med et eksempel på brug af en klasse.

In [222]:
import eksempel_modul

print(eksempel_modul.BESKED)
print(eksempel_modul.læg_sammen(3, 4))
print(eksempel_modul.kvadrer(5))

Hej fra eksempel_modul!
7
25
