# 1: NumPy

Når man er blevet mere vant til nogle af de muligheder Python i sig selv tilbyder, så er det meget almindeligt at udvide Pythons repertoire ved at gøre
det man kalder "at importere pakker". Pakker er udvidelser til standard
Python som basalt set kommer med en række foruddefinerede funktioner til
en lang række ting. Hvis man gerne vil arbejde med matematik, så er en af
de mest brugte pakker numpy.

For at få hentet alle de funktioner numpy kommer med, skal man først
importere pakken, hvilken man oftest vil gøre helt i starten.
Man kan importere pakken på en række måder, men en almindelig måde at
gøre det på er følgende

In [2]:
import numpy as np

På denne måde giver vi numpy pakken et navn i vores kode, i dette tilfælde
"np". Navnet vi har givet pakken skal bruges, når vi skal kalde funktioner
fra pakken. En af de vigtigste funktioner fra numpy er det man kalder et
numpy array.

For selv at lave en numpy array kan man skrive følgende:

In [3]:
mit_numpy_array = np.array([1, 2, 3])

print(mit_numpy_array)

[1 2 3]


Her kalder man en funktion fra numpy ved at skrive "np", og vi fortæller
Python at det er "array" funktionen vi kalder ved at skrive ".array" efter
"np". Det input vi giver til denne funktion er en liste med tallene 1, 2 og 3.

Arrays undersøtter aritmetiske operationer, såsom addition.

In [4]:
# Her lægger vi to numpy arrays sammen
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

numpy_array_sum = numpy_array_1 + numpy_array_2
numpy_array_differens = numpy_array_1 - numpy_array_2

print("sum:", numpy_array_sum)
print("differens:", numpy_array_differens)

sum: [1 2 4]
differens: [1 2 2]


Man kan betragte enkelte tal i et array ved brug af [] paranteser.

In [5]:
mit_numpy_array = np.array([1, 2, 3])

første_tal = mit_numpy_array[0]
andet_tal = mit_numpy_array[1]
tredje_tal = mit_numpy_array[2]

print("første_tal:", første_tal,
     "\n andet_tal:", andet_tal,
     "\n tredje_tal:", tredje_tal)

første_tal: 1 
 andet_tal: 2 
 tredje_tal: 3


Det at referere til bestemte elementer i en række på denne her måde kaldes **indeksering**. Her skal man være opmærksom på, at Python nul-indekserer. Det betyder bare, at man starter fra nul, når man tæller.

To andre ting, der er værd at vide om numpy arrays er, at man kan bruge len() funktionen til at få længden af et array og np.append() funktionen til at tilføje tal til et array.

In [6]:
mit_numpy_array = np.array([1, 2, 3])

print("mit_numpy_array:", mit_numpy_array)
print("Længden af mit_numpy_array:", len(mit_numpy_array))

mit_numpy_array = np.append(mit_numpy_array, 4)

print("mit_numpy_array:", mit_numpy_array)
print("Længden af mit_numpy_array:", len(mit_numpy_array))

mit_numpy_array: [1 2 3]
Længden af mit_numpy_array: 3
mit_numpy_array: [1 2 3 4]
Længden af mit_numpy_array: 4


Numpy arrays minder lidt om vektorer fra matematik og er dermed
enormt brugbare til at regne på netop vektorer i Python. Man kan også lægge to arrays i forlængelse af hinanden ved brug af concatenate funktionen, også fra numpy.

In [7]:
# Her lægger vi to numpy arrays i forlængelse af hinanden
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

numpy_array_total = np.concatenate([numpy_array_1, numpy_array_2])

print(numpy_array_total)

[1 2 3 0 0 1]


numpy kan også bruges til, at regne med matricer. Her kan man tænke på matricer som arrays af flere dimensioner

In [8]:
min_matrix = np.array([[1, 2], [3, 4]])

print(min_matrix)

[[1 2]
 [3 4]]


Hvis man gerne vil lave operationer med matricer, såsom at lægge to sammen eller trække en fra en anden, så bruger man bare de almindelige operationer
"+" og "-". Matrixmultiplikation med arrays bruger dog @ i stedet for *.

In [9]:
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[2, 2], [2, 2]])

matrix_sum = matrix_1 + matrix_2
matrix_differens = matrix_1 - matrix_2
matrix_produkt = matrix_1 @ matrix_2

print("matrix_sum:\n", matrix_sum,
      "\n matrix_differens:\n", matrix_differens,
      "\n matrix_produkt:\n", matrix_produkt)

matrix_sum:
 [[3 4]
 [5 6]] 
 matrix_differens:
 [[-1  0]
 [ 1  2]] 
 matrix_produkt:
 [[ 6  6]
 [14 14]]


Hvis man vil have prikproduktet af to arrays kan man bruge np.dot

In [10]:
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

prikprodukt = np.dot(numpy_array_1, numpy_array_2)

print(prikprodukt)

3


Man kan også transponere og invertere matricer.

In [11]:
min_matrix = np.array([[1, 2], [3, 4]])

min_transponerede_matrix = min_matrix.T    # Man kan også bruge np.transpose() i stedet for .T
min_inverterede_matrix = np.linalg.inv(min_matrix)

print("min_matrix:\n", min_matrix,
      "\n min_transponerede_matrix:\n", min_transponerede_matrix,
      "\n min_inverterede_matrix:\n", min_inverterede_matrix)

min_matrix:
 [[1 2]
 [3 4]] 
 min_transponerede_matrix:
 [[1 3]
 [2 4]] 
 min_inverterede_matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


En anden numpy funktion, som kan være relevant når man arbejder med
lineær algebra, er np.shape(). Dette er en funktion, der tager et array som
input og giver et output, der tilsvarer dimensionen af det input man har
givet funktionen. Dette kan være ret praktisk når man gerne vil undersøge
om de matricer og vektorer man arbejder med faktisk har de dimensioner,
som man forventer at de har.

In [12]:
min_matrix = np.array([[1, 2], [3, 4]])

min_matrix_dimension = np.shape(min_matrix)

print(min_matrix_dimension)

(2, 2)


Nu er det ikke så svært igen at se, at vores matrix er en 2×2 matrix,
men hvis man arbejder med meget større datasæt og matricer, så er det
pludseligt ikke så nemt at se at ens matrix er 1572 × 489 eller hvad den nu
måtte være. Der er np.shape() meget brugbar.

Der findes selvfølgelig et hav af andre ting som numpy er i stand til at gøre,
og her er internettet virkelig jeres bedste ven. Herunder er der lavet en tabel
med nogle af de mere gængse funktioner i numpy relateret til
matematik og statistik, men hvis man skal ud i noget mere specifikt så er
en hurtig søgning på nettet ofte meget hjælpsom.

| Numpy Funktion   | Beskrivelse |
|------------------|-------------|
| np.sin()         | Dette giver dig sinus til hvad end input du giver funktionen. |
| np.cos()         | Dette giver dig cosinus til hvad end input du giver funktionen. |
| np.tan()         | Dette giver dig tangens til hvad end input du giver funktionen. |
| np.exp()         | Dette tager e^x af hvad end input du giver funktionen. |
| np.pi            | Dette giver dig værdien af pi. |
| np.mean()        | Dette giver gennemsnittet af det input du giver. |
| np.var()         | Dette giver variansen af det input du giver. |
| np.std()         | Dette giver standardafvigelsen af det input du giver. |
| np.zeros()       | Dette giver dig en numpy array fyldt med nuller som har en længde tilsvarende den værdi du giver som input. |
| np.dot()         | Dette udfører matrix-vektor eller matrix-matrix multiplikation. |
| np.linalg.inv()  | Dette giver den inverse af en matrix. |
| .T               | Dette transponerer et array. |
| @                | Dette bruges til matrixmultiplikation. |

Når det kommer til matricer er indeksering lidt spøjst, da en matrix er et array, som består af arrays.

In [13]:
min_matrix = np.array([[1, 2], [3, 4]])

første_række = min_matrix[0]
første_tal = min_matrix[0][0]

print("Første element i matrix (første række):", første_række,
     "\n Første element i første element i matrix (første tal i første række):", første_tal)

Første element i matrix (første række): [1 2] 
 Første element i første element i matrix (første tal i første række): 1


Man kan også udvælge et specifikt interval af et array ved brug af kolon. Dette kaldes også "slicing"

In [14]:
mit_numpy_array = np.array([6, 4, 2, 0, 9])

print(mit_numpy_array[1:4])

[4 2 0]


Kolon kan bruges uden indsættelse af tal. I så fald bliver hele arrayet taget. Dette kan bruges til at lave operationer på kolonner i stedet for rækker.

In [15]:
min_matrix = np.array([[1, 2], [3, 4]])

print(min_matrix[:,0])

[1 3]


Her skal det forstås som at man tager alle rækker (derfor brug af kolon) men kun første kolonne (derfor brug af 0-indeksering). Her kommer der lidt flere eksempler man kan bruges som opslagsværk.

In [16]:
matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_2 = np.array([[4, -1, 6], [2, 8, -3], [2, -4, -5]])

print("Summen af de 2 første tal i anden række i første matrix og de 2 første tal i tredje række i anden matrix:", matrix_1[1, 0:2] + matrix_2[2, 0:2])
print("Differensen mellem de 2 første tal i sidste kolonne i første matrix og de 2 første tal i andensidste kolonne i anden matrix:", matrix_1[0:2, -1] - matrix_2[0:2, -2])

Summen af de 2 første tal i anden række i første matrix og de 2 første tal i tredje række i anden matrix: [6 1]
Differensen mellem de 2 første tal i sidste kolonne i første matrix og de 2 første tal i andensidste kolonne i anden matrix: [ 4 -2]


Her er der en tabel over typiske numpy funktioner, der bruges til at manipulere arrays.

| Numpy-funktion                                     | Beskrivelse                                                                                       |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
|  np.array()                                        | Dette opretter en numpy array baseret på en liste eller en anden sekvens af data.                 |
|  a[i]                                              | Standard indeksering. Refererer til elementet på position `i` (0-baseret).                        |
|  a[-1]                                             | Negativ indeksering. `-1` er **sidste** element, `-2` næstsidste osv.                             |
|  a[start:stop]                                     | Slicing. Tager et udsnit fra `start` til **ikke-inkl.** `stop`.                                   |
|  :                                                 | Tager en hel akse. Eksempelvis giver `a[:, 0]` første kolonne.                                    |                        
|  np.concatenate((a, b), axis=0)                    | Kæder arrays langs en eksisterende akse.                                                          |
|  np.stack((a, b), axis=0)                          | Samler arrays langs en **ny** akse (giver én dimension ekstra).                                   |
|  np.hstack((a, b))                                 | Horisontal stak (axis = 1 for 2-D) – svarer til `np.concatenate` med `axis=1`.                    |
|  np.vstack((a, b))                                 | Vertikal stak (axis = 0 for 2-D).                                                                 |
|  np.split(a, sections, axis=0)                     | Deler et array i flere dele langs en akse.                                                        |
|  a.reshape(new_shape)                              | Returnerer et **view** med ny form (hvis muligt uden kopiering).                                  |
|  a.flatten()                                       | Flader array til 1-D (henholdsvis view eller kopi).                                               |
|  np.shape                                          | Dette giver formen (dimensionerne) af en numpy array.                                             |

### Opgaver

##### Opgave 1.1
Definer to numpy arrays derefter print følgende:
- Teksten "mine arrays:" efterfulgt af de to arrays
- Første element i første array
- Summen af de to arrays
- Produktet af de to arrays
- Differensen mellem første tal i første array og andet tal i andet array
- En sammensætning (concatenation) af begge arrays

In [17]:
# Din kode her

##### Opgave 1.2
Tilføj (append) et tal til første array fra opgave 1.1. Derefter læg længden af det første array fra opgave 1.1 sammen med længden af det andet array fra opgave 1.1.

In [18]:
# Din kode her

##### Opgave 1.3
Definer følgende to matricer ved brug af numpy

$$
A =
\begin{bmatrix}
8 & 32 \\
9 & 1
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
5 & 4 \\
2 & 6
\end{bmatrix}
$$

Beregn følgende:

- $A + B$
- $A - B$
- $AB$
- $A^TB$
- $A^{-1}B$
- $A^{-1}A$

In [19]:
# Din kode her

##### Opgave 1.4
Tag udganspunkt i matricerne $A$ og $B$ fra før. Beregn følgende:
- Summen af første række i $A$ og anden række i $B$
- Differensen mellem første kolonne i $A$ og anden kolonne i $B$
- Produktet af første tal i første række i $A$ og andet tal af anden række i $B$

In [20]:
# Din kode her

# 2: Løkker

En computer er rigtig god til at gentage sig selv, og gøre den samme handling igen og igen. For at fortælle Python, at vi gerne vil have en handling
gentaget, så skal vi gøre brug af løkker. Der findes to slags løkker: while-løkker og for-løkker.

#### While-løkker
En while-løkke er en måde at fortælle Python, at vi gerne vil have gentaget
en handling, så længe et eller andet boolesk udtryk er sandt. Vi kan eksempelvis have

In [21]:
i = 0

while(i < 5):
    print("i har værdien:" + str(i))
    i = i+1
    
print("Nu er løkken færdig")

i har værdien:0
i har værdien:1
i har værdien:2
i har værdien:3
i har værdien:4
Nu er løkken færdig


I en while-løkkes betingelse kan vi skrive lige så komplicerede udtryk,
som vi så i afsnittet om if-else.
En while-løkke har altså formen:

In [22]:
# Før løkken
# while <betingelse>:
#   Kode der skal gentages
# Efter løkken

Bemærk igen brugen af kolon og indrykning, og i det hele taget hvor
meget det minder om en if-sætning.

Her er nogle flere eksempler.

In [23]:
min_variabel = 0
print("min_variabel før while-løkken:", min_variabel)

while min_variabel <= 10:
    min_variabel = min_variabel +1

print("min_variabel efter while-løkke:", min_variabel)

min_variabel før while-løkken: 0
min_variabel efter while-løkke: 11


In [24]:
mit_numpy_array = []
print("mit_numpy_array før while-løkken:", mit_numpy_array)

while len(mit_numpy_array) < 5:
    mit_numpy_array = np.append(mit_numpy_array, 0)

print("mit_numpy_array efter while-løkke:", mit_numpy_array)

mit_numpy_array før while-løkken: []
mit_numpy_array efter while-løkke: [0. 0. 0. 0. 0.]


Når man laver en while-løkke skal man være opmærksom på, at betingelsen ikke altid skal være sand, da løkken ellers kører uendeligt. Udkommenterer man cellen nedenfor kan man se sådan et eksempel.

In [25]:
# må_jeg_spise_børn = False

# while må_jeg_spise_børn == False:
#     print("Nej mate tag dig lige sammen er du fuldstændig blæst i kasketten eller hvad?")

#### For-løkker
En for-løkke er lavet til at gentage en handling for hvert tal i et array.
Dette er egentlig løgn, men det forsimpler forklaringen lidt. Lad os se et eksempel på en for-løkke med et array


In [26]:
mit_array = np.array([0, 1, 2, 3, 4])

for i in mit_array:
    print(i)

0
1
2
3
4


Koden skal læses som: vi lader variablen i referere skiftevis til hvert
tal i arrayet og printer tallet, for hver iteration. Eksemplet ovenfor er lidt banalt, da vi har et array der bare tæller op, så lad os se på nogle flere eksempler

In [27]:
mit_array = np.array([3, 2, 9, -2, 0.2])

print("for-løkke der printer tal i et array:")
for i in mit_array:
    print(i)

print("for-løkke der printer tal i et array efterfulgt af udråbstegn:")
for i in mit_array:
    print(i, "!")

print("\nfor-løkke der printer tal i et array plus 2")
for i in mit_array:
    print(i+2)

print("\nfor-løkke der printer alle tal i et array med en værdi større end 2")
for i in mit_array:
    if i>=2:
        print(i)

for-løkke der printer tal i et array:
3.0
2.0
9.0
-2.0
0.2
for-løkke der printer tal i et array efterfulgt af udråbstegn:
3.0 !
2.0 !
9.0 !
-2.0 !
0.2 !

for-løkke der printer tal i et array plus 2
5.0
4.0
11.0
0.0
2.2

for-løkke der printer alle tal i et array med en værdi større end 2
3.0
2.0
9.0


Man behøver ikke bruge bogstavet $i$ som indeks i en for-løkke, men det er en konvention, som vi anbefaler at følge. Vær opmærksom på brug af $[i]$ i forhold til $i$ til indeksering i en for-løkke. Man kan også lave såkaldte "nestede" løkker, som er løkker i andre løkker. Her bliver man nødt til at bruge flere forskellige bogstaver til indeksering, hvilket hurtigt bliver meget nørklet, men kan være brugbart.

Betragt nedenstående eksempler.

In [28]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([2, 2, 2, 2, 2, 2])

for i in array_1:
    for j in array_2:
        print("waouw sejt tal", i+j)

waouw sejt tal 3
waouw sejt tal 3
waouw sejt tal 3
waouw sejt tal 3
waouw sejt tal 3
waouw sejt tal 3
waouw sejt tal 4
waouw sejt tal 4
waouw sejt tal 4
waouw sejt tal 4
waouw sejt tal 4
waouw sejt tal 4
waouw sejt tal 5
waouw sejt tal 5
waouw sejt tal 5
waouw sejt tal 5
waouw sejt tal 5
waouw sejt tal 5


In [29]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indeks_array = np.array([0, 1, 2])
matrix_par_sum = np.array([])

for i in indeks_array:
    for j in indeks_array:
        matrix_par_sum = np.append(matrix_par_sum, matrix[i, j] + matrix[j, i])

print("matrix_par_sum:", matrix_par_sum)

matrix_par_sum: [ 2.  6. 10.  6. 10. 14. 10. 14. 18.]


### Opgaver

##### Opgave 2.1
Følgende kode printer alle tal i et array plus 2. Gør så den i stedet printer alle tal i arrayet ganget med 5.

In [30]:
mit_array = np.array([0, 1, 2, 3, 4])

for i in mit_array:
    print(i + 2)

2
3
4
5
6


##### Opgave 2.2
Lav et program, der definerer et array og en for-løkke, der kvadrerer (opløfter i anden) alle tal i arrayet.

In [31]:
# Din kode her

##### Opgave 2.3
Lav et program, der definerer et array og en for-løkke, der trækker de sidste 3 tal i arrayet fra de første 3 tal i arrayet. 

In [32]:
# Din kode her

##### Opgave 2.4
Lav et program der definerer en variabel, som indeholder et positivt tal og derefter en while-løkke som trækker 1 fra variablen indtil den rammer 0. Print hvor mange gange der skulle tælles ned før while-løkken stoppede.

In [33]:
# Din kode her

##### Opgave 2.5
Følgende kode forsøger at udskrive alle tallene i arrayet. Hvad gør koden egentlig? Find problemet/problemerne og løs det/dem.

In [34]:
L = np.array([5, 2, 4, 1])
i = 1
while i <= len(L):
    print(L[i])
    i = i + 1

2
4
1


IndexError: index 4 is out of bounds for axis 0 with size 4

##### Opgave 2.6
Følgende udkommenterede program vil gerne printe alle de tal i listen, der er
mindre end $5$. Hvad gør koden egentlig? Omskriv while-løkken til en for-løkke

In [ ]:
# L = np.array([6, 1, 10, 11, 4, 2, 3])
# i = 0
# while i < len(L):
#     if L[i] < 5:
#         print(i)

##### Opgave 2.7
Skriv et program, der definerer et array, og derefter udskriver summen af tallene i et array ved hjælp af en løkke.

In [ ]:
# Din kode her

##### Opgave 2.8
Skriv et program, der definerer et array og printer "jeg kan lide kage", for hver gang der er et negativt tal i arrayet.

In [ ]:
# Din kode her

##### Opgave 2.9
Skriv et program der definerer en 3 x 3 matrix og lægger 1 til hvert tal i matricen indtil summen af alle tallene er større end 100. Sørg for at definere og printe et array, der indeholder alle summerne ved at tilføje sum til et array for hver iteration.

In [ ]:
# Din kode her

##### Opgave 2.10
Skriv et program, der indlæser et array af tal og udskriver det
mindste tal i arrayet efterfulgt af det første tal i arrayet.

In [ ]:
# Din kode her

# 3: Funktioner

Funktioner er en af de grundlæggende måder at strukturere sin kode på. De gør det nemmere at gentage beregninger, og kan gøre kode mere ordnet. Lad os først starte med at kigge på et eksempel på, hvorfor funktioner er brugbare.

In [ ]:
a = 3
b = 4

c = (a**2 + b**2)**(1/2)

print(c)

a = 5
b = 12

c = (a**2 + b**2)**(1/2)

print(c)

a = 6
b = 8

c = (a**2 + b**2)**(1/2)

print(c)

5.0
13.0
10.0


Her beregner og printer vi $c$ i Pythagoras læresætning 3 gange på præcis samme måde hver gang. Hvis man i stedet havde en funktion der lavede beregningen og printede, for forskellige værdier af $a$ og $b$, så ville man undgå at skulle skrive hele smøren op om og om igen. I tilfældet her vil det se ud som følgende:

In [ ]:
def pythagoras(a, b):
    c = (a**2 + b**2)**(1/2)
    print(c)

pythagoras(3, 4)
pythagoras(5, 12)
pythagoras(6, 8)

5.0
13.0
10.0


Ligesom med betingelsessætninger skrives en funktion op med et nøgleord (her er det *def* i stedet for eksempelvis *if*) paranteser, kolonner og indryk. Her giver vi dog funktionen en navn (pythagoras her), der så skrives op, når vi kalder (bruger) funktionen.

Helt kort fortalt er følgende skabelonen for at definere sin egen funktion:

In [ ]:
# def <funktionsnavn>(<arg1>,<arg2 >,...):
    # kode. Funktionens "krop".
    # return <værdi> # Valgfri

En funktionsdefinition består af 4 forskellige elementer:

- Et **navn**: Dette er navnet, man bruger, når man skal kalde en funktion:
I eksemplet er navnet pythagoras. Når man definerer en funktion, skal
man altid skrive def inden da, så Python ved, at der er tale om en
funktion.
- En **krop**: Dette er koden, som kører, når funktionen bliver kaldt,
altså når der er et stykke kode, som beder om at køre funktionen.
Eksemplets krop er linjen $c = (a**2 + b**2)**(1/2)$.
- En række **argumenter** (valgfrit): Dette er input, som funktionen
modtager, og kaldes også for parametre. Eksemplet tager 1 argument:
liste, som skal være en liste af tal. Det er muligt at have funktioner, der modtager 0 argumenter,
så skriver man ingenting imellem parenteserne, men parenteserne skal
stadig være der.
- En **returværdi** (valgfrit): Det er dette resultat, som funktionen giver
tilbage til det stykke kode, der kaldte den. Eksemplet ovenfor har ikke noget returelement, men vi ser senere på eksempler med returværdier.

Lad os se på lidt flere eksempler på funktioner

In [ ]:
def f(x):
    y = 2 * x + 2
    return y

print("Lineær funktion y = 2 * x + 2 kaldt på 2:", f(2))
print("Lineær funktion y = 2 * x + 2 kaldt på 3:", f(3))
print("Lineær funktion y = 2 * x + 2 kaldt på 4:", f(4))

Lineær funktion y = 2 * x + 2 kaldt på 2: 6
Lineær funktion y = 2 * x + 2 kaldt på 3: 8
Lineær funktion y = 2 * x + 2 kaldt på 4: 10


In [ ]:
def kvadrer_tal_i_array(array):
    for i in array:
        print(i**2)

sejt_array = np.array([2,3,4])
print(kvadrer_tal_i_array(sejt_array))

4
9
16
None


Ovenstående funktion virker faktisk både på tal og arrays, men funktioner, der itererer gennem et array virker ikke altid hensigtsmæssigt på tal. Bemærk der bliver printet None fordi der bliver printet uden funktionen har en returværdi.

In [ ]:
def pølsechef_her_hvad_kunne_du_tænke_dig(episk_pølsebestilling):
    bommelommelom_emil_fra_pølseberg = np.array([])
    for pølle in episk_pølsebestilling:
        pølle += 1   
        bommelommelom_emil_fra_pølseberg = np.append(bommelommelom_emil_fra_pølseberg, f(pølle))
    print("Her værsgo bro der har du din episke ristede bro håber du har en god dag jeg hader virkelig mit arbejde xd", bommelommelom_emil_fra_pølseberg)

jeg_kunne_godt_tænke_mig_en_ristet_med_det_hele_tak = np.array([2,3,4])
pølsechef_her_hvad_kunne_du_tænke_dig(jeg_kunne_godt_tænke_mig_en_ristet_med_det_hele_tak)

Her værsgo bro der har du din episke ristede bro håber du har en god dag jeg hader virkelig mit arbejde xd [ 8. 10. 12.]


Faktisk har vi allerede set på flere forskellige funktioner herunder print(), np.array() og len(). Det at bruge funktioner er altså slet ikke så nyt igen, men nu kan du selv være med til at lave dem 8) 

### Opgaver


##### Opgave 3.1
Lav et program der tager et tal $x$ som input og returnerer $x + 2$.

In [ ]:
# Din kode her

##### Opgave 3.2
Lav et program med en funktion der berenger $y = 2 \cdot x^2 + 2$ med $y$ som returværdi og $x$ som input. Print derefter resultatet af, at kalde funktionen på 3 forskellige input.

In [ ]:
# Din kode her

##### Opgave 3.3
Lav et program med en funktion, der tager et array som input og returnerer gennemsnittet af tallene i arrayet.

In [ ]:
# Din kode her

##### Opgave 3.4
Skriv et program som afgører, hvorvidt en matrix er symmetrisk eller ej. Her menes der
med symmetrisk at matricen opfylder $A^T = A$

In [ ]:
# Din kode her

##### Opgave 3.5
Skriv et program som finder og returnerer middelværdien og variansen af hver række i en vilkårlig matrix. Hint: Brug tabellen over indbyggede numpy funktioner.

In [ ]:
# Din kode her

##### Opgave 3.6
En andengradsligning er en ligning på formen $ax^2 +bx+c =
0$, hvor målet er at finde x. Skriv et program med en funktion, der tager 3 input $a$, $b$ og $c$ og printer antallet af løsninger til ligningen, samt
løsningerne til ligningen, hvis de findes.

Antallet af løsninger kan bestemmes ud fra diskriminanten $d = b^2 − 4ac$
som følger:

- $d < 0$: Der findes ingen reelle løsninger.
- $d = 0$: Der findes én løsning $x = \frac{-b}{2a}−b$
- $d > 0$: Der findes to løsninger givet ved $x = \frac{−b±\sqrt{d}}{2a}$

In [ ]:
# Din kode her

# 4: Lister og dictionaries

Indtil nu har vi arbejdet med arrays, som er oplagte når man har numerisk data man vil regne på. Nogle gange har man dog data der ikke er tal, eller data der ikke passer ind i et pænt gitter. Her kommer lister ind i billedet

Lister er Pythons måde at gemme en samling af ting på. De minder meget om arrays, men kan indeholde forskellige typer data fremfor kun tal, og man behøver ikke importere noget for at bruge dem.

In [ ]:
# En liste laves med firkantede parenteser
frugter = ["æble", "banan", "citron"]
tal = [3, 1, 4, 1, 5, 9]
blandet = [42, "tekst", 3.14, True]

# Man kan tilgå elementer ligesom med arrays (0-indekseret)
print(frugter[0])      # "æble"
print(frugter[-1])     # "citron" (negativ index tæller bagfra)

# Man kan tilføje elementer med .append()
frugter.append("drage")
print(frugter)         # ["æble", "banan", "citron", "drage"]

# Og man kan slice ligesom med arrays
print(tal[1:4])        # [1, 4, 1]

# Længden findes med len()
print(len(frugter))    # 4

# Løkker virker også
for frugt in frugter:
    print(frugt)

æble
citron
['æble', 'banan', 'citron', 'drage']
[1, 4, 1]
4
æble
banan
citron
drage


På overfladen lyder lister smartere, men de håndterer matematiske operationer på en helt anden måde

In [5]:
liste_a = [1, 2, 3]
liste_b = [6, 7, 69]

print(liste_a + liste_b)

[1, 2, 3, 6, 7, 69]


Tommerfingerreglen er at bruge arrays til nummerisk data (fx måledata til plotting og fitting), og lister til samlinger af ting der ikke nødvendigvis er tal.

Dictionaries er en anden måde at gemme data på, men i stedet for at tilgå elementer via et index-tal, bruger man nøgler (keys). Tænk på det som en ordbog: du slår et ord op (nøglen) og får en forklaring (værdien).

In [ ]:
# En dictionary laves med krøllede parenteser
person = {
    "navn": "Anna",
    "alder": 17,
    "klasse": "2.g",
    "interesser": ["matematik", "astronomi", "kodning"]
}

# Man tilgår værdier via nøglen
print(person["navn"])          # "Anna"
print(person["interesser"][1]) # "astronomi"

# Man kan tilføje nye nøgle-værdi-par
person["skole"] = "HTX Lyngby"
print(person["skole"])         # "HTX Bjerringbro"

# Man kan også ændre eksisterende værdier
person["alder"] = 18

Anna
astronomi
HTX Bjerringbro


Man kan loope over en dictionary på flere måder

In [7]:
# Looper over nøglerne
for nøgle in person:
    print(nøgle, "→", person[nøgle])

# Eller begge dele på én gang med .items()
for nøgle, værdi in person.items():
    print(f"{nøgle}: {værdi}")

navn → Anna
alder → 18
klasse → 2.g
interesser → ['matematik', 'astronomi', 'kodning']
skole → HTX Bjerringbro
navn: Anna
alder: 18
klasse: 2.g
interesser: ['matematik', 'astronomi', 'kodning']
skole: HTX Bjerringbro


Dictionaries er praktiske når man har data der naturligt kan "mærkes" med et navn fremfor et index Eksempelvis kunne man finde på at bruge dictionaries ofte til at gemme hyperparametre og resultater, når man laver machine learning (mere om det senere)

In [9]:
resultater = {
    "model_1 (lineær regression)": {"R2": 0.87, "grad": 1},
    "model_2 (neuralt netværk)": {"R2": 0.93, "grad": 2},
    "model_3 (Support Vector Machines)": {"R2": 0.91, "grad": 3},
}

for navn, resultat in resultater.items():
    print(f"{navn}: R²={resultat['R2']}, polynomiegrad={resultat['grad']}")

model_1 (lineær regression): R²=0.87, polynomiegrad=1
model_2 (neuralt netværk): R²=0.93, polynomiegrad=2
model_3 (Support Vector Machines): R²=0.91, polynomiegrad=3


Her kan det give bedre mening at bruge navnet på modellen som nøgle fremfor indeks, da det gør koden mere læsbar og selvforklarende.

### Opgaver

##### Opgave 2.1

Opret en liste med mindst fem af dine yndlingsfilm. Brug derefter en løkke til at printe hver film med et nummer foran, så eksempelvis
1. Interstellar
2. The Matrix
3. Kung Fury
osv.

Hint: Du kan bruge range(len(filmliste)) eller enumerate() til at få både index og film.

##### Opgave 2.2

Opret en dictionary der beskriver dig selv. Som minimum skal den indeholde dit navn, din alder, din skole og en liste af dine interesser. Brug derefter en løkke med .items() til at printe alt informationen pænt.

##### Opgave 2.3

Lav en dictionary kaldet vareliste der simulerer en indkøbskurv med mindst fem varer og deres priser, så eksempelvis

vareliste = {
    "mælk": 12,
    "brød": 20,
    "æg": 25,
    ...
}

Brug derefter en løkke til at beregne og printe den samlede pris for alle varer i indkøbskurven.

Hint: Start med en variabel total = 0 og læg prisen fra hver vare til i løkken.

# 5: Klasser og moduler